
const STORAGE_KEY='toeic_v7_4_state';
const SETTINGS_KEY='toeic_v7_4_settings';
const DAILY_NEW=8,DAILY_MIN=24,DAILY_MAX=32,REVIEW_LIMIT=24,DAILY_MASTER_TARGET=2;
const APP_SCHEMA_VERSION=74;
const SRS_STEPS=[0,1,3,7,14,30,45,90];
const HARD_STEPS=[0,1,2,4,7];
const LAPSE_PENALTY=2;
const OVERDUE_BONUS_CAP=20;

function todayStr(){return new Date().toISOString().slice(0,10)}
function addDays(s,d){const x=new Date(s+'T00:00:00');x.setDate(x.getDate()+d);return x.toISOString().slice(0,10)}
function diffDays(from,to){const a=new Date(from+'T00:00:00');const b=new Date(to+'T00:00:00');return Math.floor((b-a)/86400000)}
function getOverdueDays(word,today=todayStr()){if(!word?.nextReview)return 0;return Math.max(0,diffDays(word.nextReview,today))}
function getSrsLevel(word){return Math.max(0,Number(word?.reviewStep||0))}
function ensureWordFields(word){if(word.lapses==null)word.lapses=0;if(word.streak==null)word.streak=0;if(word.lastResult==null)word.lastResult='';if(word.dueStreak==null)word.dueStreak=0;return word}
function getPriorityScore(word,today=todayStr()){ensureWordFields(word);const overdue=getOverdueDays(word,today);const needMaster=(DAILY_MASTER_TARGET-(word.todayScore||0))*8;const wrongBoost=(word.todayWrong||0)*18;const lapseBoost=(word.lapses||0)*6;const weakBoost=(5-(word.mastery||0))*3;const overdueBoost=Math.min(OVERDUE_BONUS_CAP,overdue*4);return needMaster+wrongBoost+lapseBoost+weakBoost+overdueBoost}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function masteryColor(m){if(m<=1)return'red';if(m<=3)return'yellow';return'green'}
function getStudyWords(){return Object.values(state.words)}
function escapeRegExp(s){return String(s||'').replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function getPrimaryMeaning(meaning){return String(meaning||'').split(/[；;、,，/]/).map(x=>x.trim()).find(Boolean)||'這個字'}
function getExampleSubject(w){const meaning=getPrimaryMeaning(w?.meaning);return /常用字$/.test(meaning)?`單字「${w.word}」`:`「${meaning}」`}
function needsExampleZhRepair(w){const zh=String(w?.example_zh||'').trim();if(!zh)return true;const word=String(w?.word||'').trim();if(word&&new RegExp(`\\b${escapeRegExp(word)}\\b`,'i').test(zh))return true;const asciiLetters=(zh.match(/[A-Za-z]/g)||[]).length;return asciiLetters>=Math.max(4,Math.floor(zh.length*0.2))}
function isTemplateMeaning(w){return /^[一-龥]{2,4}常用字$/.test(String(w?.meaning||'').trim())}
function hasTemplateExample(w){const en=String(w?.example_en||'').trim();return EXAMPLE_ZH_PATTERNS.some(([p])=>p.test(en))}
function hasReliableExample(w){return Boolean(String(w?.example_en||'').trim()&&String(w?.example_zh||'').trim())}
const EXAMPLE_ZH_PATTERNS=[
[/^The manager discussed the .+ during the meeting\.$/i,m=>`經理在會議中討論了${m}這個主題。`],
[/^The finance team reviewed the .+ before making payment\.$/i,m=>`財務團隊在付款前審查了${m}這項內容。`],
[/^The HR department mentioned .+ during the interview\.$/i,m=>`人資部門在面試過程中提到了${m}。`],
[/^Please check the .+ before your trip begins\.$/i,m=>`出發前請先確認${m}這項內容。`],
[/^We added .+ to tomorrow's agenda\.$/i,m=>`我們把${m}加入明天的議程。`],
[/^The campaign focused on .+ this quarter\.$/i,m=>`這一季的行銷活動聚焦於${m}。`],
[/^The warehouse updated the .+ before shipment\.$/i,m=>`出貨前，倉庫更新了${m}這項資料。`],
[/^I mentioned .+ in the email to the client\.$/i,m=>`我在寄給客戶的郵件中提到了${m}。`],
[/^The IT team tested the .+ before release\.$/i,m=>`資訊團隊在發布前測試了${m}這項內容。`],
[/^The sales team used .+ to close the deal\.$/i,m=>`業務團隊運用${m}完成了這筆交易。`],
];
function getExampleEn(w){if(!w)return'';if(!hasReliableExample(w))return 'This entry currently has no verified example sentence.';return w.example_en}
function getExampleZh(w){if(!w)return'';if(!hasReliableExample(w))return '這個單字目前沒有可信的例句與翻譯，暫時不顯示錯誤內容。';return w.example_zh}

function readSettings(){const raw=localStorage.getItem(SETTINGS_KEY);const fb={apiBaseUrl:(window.APP_CONFIG&&window.APP_CONFIG.API_BASE_URL)||'',syncCode:''};if(!raw)return fb;try{return {...fb,...JSON.parse(raw)}}catch{return fb}}
function writeSettings(s){localStorage.setItem(SETTINGS_KEY,JSON.stringify(s))}
function getOrCreateSyncCode(){const s=readSettings();if(s.syncCode)return s.syncCode;s.syncCode='sync-'+Math.random().toString(36).slice(2,10)+'-'+Math.random().toString(36).slice(2,8);writeSettings(s);return s.syncCode}
function setSyncCode(v){v=(v||'').trim();if(!v)return false;const s=readSettings();s.syncCode=v;writeSettings(s);return true}

function getLibrarySignature(){const list=Array.isArray(window.WORDS)?window.WORDS:[];const count=list.length;const lastId=count?list[count-1].id:0;const lastWord=count?list[count-1].word:'';return `schema:${APP_SCHEMA_VERSION}|count:${count}|lastId:${lastId}|lastWord:${lastWord}`}
function makeFreshWordState(w,oldWord=null){return {...w,mastery:oldWord?.mastery??0,seen:oldWord?.seen??false,wrongCount:oldWord?.wrongCount??0,learnedAt:oldWord?.learnedAt??null,lastReviewed:oldWord?.lastReviewed??null,nextReview:oldWord?.nextReview??null,reviewStep:oldWord?.reviewStep??0,todayScore:0,todayWrong:0,todayCorrect:0,lapses:oldWord?.lapses??0,streak:oldWord?.streak??0,dueStreak:oldWord?.dueStreak??0,lastResult:oldWord?.lastResult??''}}
function buildInitialState(oldState=null){const oldById=oldState?.words||{};const oldByWord={};for(const item of Object.values(oldById)){if(item&&item.word)oldByWord[item.word]=item}const words={};for(const w of window.WORDS){const oldWord=oldById[w.id]&&oldById[w.id].word===w.word?oldById[w.id]:(oldByWord[w.word]||null);words[w.id]=makeFreshWordState(w,oldWord)}return {schemaVersion:APP_SCHEMA_VERSION,librarySignature:getLibrarySignature(),currentRoute:oldState?.currentRoute||'home',filters:oldState?.filters||{topic:'all',level:'all'},selectedWordId:null,words,sessions:{},history:oldState?.history||[],sync:oldState?.sync||{lastCloudLoad:null,lastCloudSave:null,cloudEnabled:false}}}
function saveLocalState(s){s.schemaVersion=APP_SCHEMA_VERSION;s.librarySignature=getLibrarySignature();localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}
function loadLocalState(){const raw=localStorage.getItem(STORAGE_KEY);if(raw){try{const parsed=JSON.parse(raw);const sameSchema=parsed?.schemaVersion===APP_SCHEMA_VERSION;const sameLibrary=parsed?.librarySignature===getLibrarySignature();if(sameSchema&&sameLibrary)return parsed;const rebuilt=buildInitialState(parsed);saveLocalState(rebuilt);return rebuilt}catch{}}const initial=buildInitialState();saveLocalState(initial);return initial}

async function loadCloudStateIfPossible(){const settings=readSettings();const api=(settings.apiBaseUrl||'').trim().replace(/\/+$/,'');const syncCode=getOrCreateSyncCode();if(!api)return null;try{const res=await fetch(api+'/load?syncCode='+encodeURIComponent(syncCode));if(!res.ok)throw new Error('HTTP '+res.status);const data=await res.json();if(data&&data.state){const merged=buildInitialState(data.state);merged.sync=merged.sync||{};merged.sync.lastCloudLoad=new Date().toISOString();merged.sync.cloudEnabled=true;return merged}return null}catch(err){console.error(err);return null}}
let cloudSaveTimer=null;
async function saveCloudState(state){const settings=readSettings();const api=(settings.apiBaseUrl||'').trim().replace(/\/+$/,'');const syncCode=getOrCreateSyncCode();if(!api)return false;try{const res=await fetch(api+'/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({syncCode,state})});if(!res.ok)throw new Error('HTTP '+res.status);return true}catch(err){console.error(err);return false}}
function scheduleCloudSave(){clearTimeout(cloudSaveTimer);cloudSaveTimer=setTimeout(async()=>{if(!window.state)return;const ok=await saveCloudState(window.state);if(ok){window.state.sync=window.state.sync||{};window.state.sync.lastCloudSave=new Date().toISOString();saveLocalState(window.state);if(window.state.currentRoute==='settings')render()}},500)}
function saveState(s){window.state=s;saveLocalState(s);scheduleCloudSave()}

function createDailyCandidateIds(){const t=todayStr();const all=getStudyWords().map(ensureWordFields);const due=all.filter(w=>w.nextReview&&w.nextReview<=t).sort((a,b)=>{const pa=getPriorityScore(a,t),pb=getPriorityScore(b,t);if(pb!==pa)return pb-pa;return(a.nextReview||'').localeCompare(b.nextReview||'')}).slice(0,REVIEW_LIMIT).map(w=>w.id);const unseen=all.filter(w=>!w.seen).sort((a,b)=>a.level-b.level||a.id-b.id).slice(0,DAILY_NEW).map(w=>w.id);const pool=[...new Set([...due,...unseen])];if(pool.length<DAILY_MIN){const extras=all.filter(w=>w.seen&&!pool.includes(w.id)).sort((a,b)=>getPriorityScore(b,t)-getPriorityScore(a,t));for(const item of extras){if(pool.length>=DAILY_MIN)break;pool.push(item.id)}}return pool.slice(0,DAILY_MAX)}
function ensureTodaySession(){const t=todayStr();if(state.sessions[t])return state.sessions[t];const ids=createDailyCandidateIds();for(const id of ids){const w=ensureWordFields(state.words[id]);w.todayScore=0;w.todayWrong=0;w.todayCorrect=0;w.lastResult=''}const s={date:t,activeIds:ids,stage:'cards',cardIndex:0,completedCards:[],completedQuiz:[],wrongIds:[],stats:{green:0,yellow:0,red:0,correct:0,wrong:0}};state.sessions[t]=s;saveState(state);return s}
function libraryDone(all){const unseen=all.filter(w=>!w.seen).length;const due=all.filter(w=>w.nextReview&&w.nextReview<=todayStr()).length;return unseen===0&&due===0}
function getUnmasteredCount(session){return session.activeIds.filter(id=>(state.words[id].todayScore||0)<DAILY_MASTER_TARGET).length}
function pickNextQuizId(session){const t=todayStr();const arr=session.activeIds.filter(id=>(state.words[id].todayScore||0)<DAILY_MASTER_TARGET).map(id=>state.words[id]).map(ensureWordFields).sort((a,b)=>getPriorityScore(b,t)-getPriorityScore(a,t));if(arr.length===0)return null;const urgent=arr.slice(0,Math.min(5,arr.length));return urgent[Math.floor(Math.random()*urgent.length)].id}
function speakWord(text){if(!('speechSynthesis' in window)){alert('這個瀏覽器不支援發音');return}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.92;window.speechSynthesis.speak(u)}
function scheduleByCard(word,grade){const t=todayStr();ensureWordFields(word);if(!word.seen){word.seen=true;word.learnedAt=t}word.lastReviewed=t;if(grade==='green'){word.streak+=1;word.lastResult='green';word.mastery=Math.min(5,word.mastery+2);word.reviewStep=Math.min(word.reviewStep+1,SRS_STEPS.length-1);word.nextReview=addDays(t,SRS_STEPS[word.reviewStep]||30)}else if(grade==='yellow'){word.streak=Math.max(0,word.streak-1);word.lastResult='yellow';word.mastery=Math.min(5,Math.max(1,word.mastery+1));word.reviewStep=Math.min(word.reviewStep+1,HARD_STEPS.length-1);word.nextReview=addDays(t,HARD_STEPS[word.reviewStep]||2)}else{word.streak=0;word.lastResult='red';word.mastery=Math.max(0,word.mastery-1);word.reviewStep=Math.max(0,word.reviewStep-LAPSE_PENALTY);word.wrongCount+=1;word.lapses+=1;word.nextReview=t}}
function scheduleByQuiz(word,ok){const t=todayStr();ensureWordFields(word);word.lastReviewed=t;if(ok){word.todayCorrect+=1;word.todayScore=Math.min(DAILY_MASTER_TARGET,word.todayScore+1);word.streak+=1;word.lastResult='correct';if(word.todayScore>=DAILY_MASTER_TARGET){word.mastery=Math.min(5,word.mastery+1);word.reviewStep=Math.min(word.reviewStep+1,SRS_STEPS.length-1);word.nextReview=addDays(t,SRS_STEPS[word.reviewStep]||30)}else{word.nextReview=addDays(t,1)}}else{word.todayWrong+=1;word.todayScore=0;word.streak=0;word.lastResult='wrong';word.mastery=Math.max(0,word.mastery-1);word.reviewStep=Math.max(0,word.reviewStep-LAPSE_PENALTY);word.wrongCount+=1;word.lapses+=1;if(word.todayWrong>=2){word.nextReview=t}else{word.nextReview=addDays(t,1)}}}
function finalizeSessionIfNeeded(){const t=todayStr(),s=state.sessions[t];if(!s||s.stage!=='done')return;const exists=(state.history||[]).some(x=>x.date===t);if(!exists){state.history.unshift({date:t,total:s.activeIds.length,correct:s.stats.correct,wrong:s.stats.wrong});if(state.history.length>30)state.history=state.history.slice(0,30);saveState(state)}}
function setTitle(title,showHome){document.getElementById('title').textContent=title;document.getElementById('homeBtn').classList.toggle('hidden',!showHome)}
function setNav(route){document.querySelectorAll('.navbtn').forEach(btn=>btn.classList.toggle('active',btn.dataset.route===route))}
function go(route){state.currentRoute=route;saveState(state);render()}
function openWordDetail(id){state.selectedWordId=id;state.currentRoute='word';saveState(state);render()}
document.getElementById('homeBtn').addEventListener('click',()=>go('home'))
document.querySelectorAll('.navbtn').forEach(btn=>btn.addEventListener('click',()=>go(btn.dataset.route)))

function getSrsSummary(){const all=getStudyWords().map(ensureWordFields);const t=todayStr();const due=all.filter(w=>w.nextReview&&w.nextReview<=t).length;const hard=all.filter(w=>(w.lapses||0)>=2).length;const learned=all.filter(w=>w.seen).length;const strong=all.filter(w=>(w.mastery||0)>=4).length;return {due,hard,learned,strong}}

function renderHome(){const s=ensureTodaySession();setTitle('今日任務',false);setNav('home');const total=s.activeIds.length,remain=getUnmasteredCount(s),done=total-remain,p=total?Math.round(done/total*100):0;const all=getStudyWords(),learned=all.filter(w=>w.seen).length,finished=libraryDone(all),srs=getSrsSummary();document.getElementById('view').innerHTML=`${finished?`<div class="card notice"><div class="section">目前字庫已練完</div><div class="muted">可以直接換新的 words_library.js。</div></div>`:''}<div class="card hero"><div class="small">v7.4：記憶曲線 + 錯題加權</div><div class="section">今日未熟 ${remain} / ${total}</div><div class="track"><div class="bar" style="width:${p}%"></div></div><div style="height:8px"></div><div class="pill">熟練條件：每字至少答對 2 次</div><div class="stack" style="margin-top:14px"><button class="btn primary" id="startBtn" type="button">${done>0?'繼續今日練習':'開始今日練習'}</button></div></div><div class="grid"><div class="metric"><div class="ml">今天字數</div><div class="mv">${total}</div></div><div class="metric"><div class="ml">剩餘未熟</div><div class="mv">${remain}</div></div><div class="metric"><div class="ml">已學過</div><div class="mv">${learned}</div></div><div class="metric"><div class="ml">正式字庫</div><div class="mv">${all.length}</div></div></div><div class="card"><div class="section">v7.4 記憶曲線</div><div class="grid"><div class="metric"><div class="ml">今日到期</div><div class="mv">${srs.due}</div></div><div class="metric"><div class="ml">高風險字</div><div class="mv">${srs.hard}</div></div><div class="metric"><div class="ml">已學過</div><div class="mv">${srs.learned}</div></div><div class="metric"><div class="ml">高熟練</div><div class="mv">${srs.strong}</div></div></div></div>`;document.getElementById('startBtn').addEventListener('click',()=>{if(s.stage==='cards')go('study');else if(s.stage==='quiz')go('quiz');else go('summary')})}
function renderStudy(){const s=ensureTodaySession();setTitle('單字卡',true);setNav('');const total=s.activeIds.length;if(s.cardIndex>=total){s.stage='quiz';saveState(state);go('quiz');return}const id=s.activeIds[s.cardIndex],w=state.words[id],exampleEn=getExampleEn(w),exampleZh=getExampleZh(w);document.getElementById('view').innerHTML=`<div class="card hero"><div class="small">第 ${s.cardIndex+1} / ${total} 張</div><div class="track"><div class="bar" style="width:${Math.round(s.cardIndex/total*100)}%"></div></div></div><div class="card"><div class="word">${w.word}</div><div class="phon">${w.phonetic}</div><div class="meta"><span class="badge">${w.pos}</span><span class="badge">${w.topic}</span><span class="badge">L${w.level}</span></div><div class="meaning">${w.meaning}</div><div class="stack" style="margin-top:12px"><button class="btn secondary" id="speakBtn" type="button">🔊 聽發音</button></div><div class="exen">${exampleEn}</div><div class="exzh">${exampleZh}</div><div class="answers"><button class="btn red" data-grade="red" type="button">不會</button><button class="btn yellow" data-grade="yellow" type="button">模糊</button><button class="btn green" data-grade="green" type="button">記得</button></div></div>`;document.getElementById('speakBtn').addEventListener('click',()=>speakWord(w.word));document.querySelectorAll('[data-grade]').forEach(btn=>btn.addEventListener('click',()=>{const g=btn.dataset.grade;scheduleByCard(w,g);if(!s.completedCards.includes(id))s.completedCards.push(id);s.stats[g]+=1;s.cardIndex+=1;saveState(state);renderStudy()}))}
function makeQuestionSentence(w){if(!hasReliableExample(w))return 'Please choose the correct word: _____';const lowerSentence=(w.example_en||'').toLowerCase();const lowerWord=(w.word||'').toLowerCase();const idx=lowerSentence.indexOf(lowerWord);if(idx===-1)return 'Please choose the correct word: _____';return w.example_en.slice(0,idx)+'_____'+w.example_en.slice(idx+w.word.length)}
function renderQuiz(){const s=ensureTodaySession();setTitle('熟練練習',true);setNav('');const nextId=pickNextQuizId(s);if(nextId==null){s.stage='done';saveState(state);finalizeSessionIfNeeded();go('summary');return}const w=state.words[nextId],remain=getUnmasteredCount(s),masked=makeQuestionSentence(w),exampleZh=getExampleZh(w);document.getElementById('view').innerHTML=`<div class="card hero"><div class="small">今天剩餘未熟 ${remain} 題</div><div class="track"><div class="bar" style="width:${Math.round((s.activeIds.length-remain)/s.activeIds.length*100)}%"></div></div></div><div class="card quiz"><div class="exen">${masked}</div><div class="meta">${w.pos} ｜ ${w.meaning} ｜ 已熟練 ${w.todayScore||0}/${DAILY_MASTER_TARGET}</div><button class="btn secondary" id="speakBtn" type="button">🔊 聽發音</button><input id="answerInput" class="input" placeholder="輸入英文單字" autocomplete="off" autocapitalize="none" spellcheck="false"><div class="stack" style="margin-top:10px"><button class="btn primary" id="checkBtn" type="button">確認答案</button></div><div id="resultBox"></div></div>`;document.getElementById('speakBtn').addEventListener('click',()=>speakWord(w.word));const input=document.getElementById('answerInput');input.focus();function nextStep(){if(!s.completedQuiz.includes(nextId))s.completedQuiz.push(nextId);saveState(state);renderQuiz();window.scrollTo({top:0,behavior:'instant'})}function showResult(ok){const box=document.getElementById('resultBox');if(ok){s.stats.correct+=1;box.innerHTML=`<div class="result good"><div><strong>答對了</strong></div><div style="margin-top:4px">${w.word}</div><div class="muted" style="margin-top:4px">${exampleZh}</div><div class="muted" style="margin-top:4px">今日熟練進度：${w.todayScore}/${DAILY_MASTER_TARGET}</div></div><div class="stack" style="margin-top:10px"><button class="btn primary" id="nextBtn" type="button">下一題</button></div>`}else{s.stats.wrong+=1;if(!s.wrongIds.includes(nextId))s.wrongIds.push(nextId);box.innerHTML=`<div class="result bad"><div><strong>答錯了</strong></div><div style="margin-top:4px">正確答案：<strong>${w.word}</strong></div><div style="margin-top:4px">${w.meaning}</div><div class="muted" style="margin-top:4px">${exampleZh}</div><div class="muted" style="margin-top:4px">這個單字今天會再次出現，直到熟練。</div></div><div class="stack" style="margin-top:10px"><button class="btn primary" id="nextBtn" type="button">繼續練習</button></div>`}document.getElementById('nextBtn').addEventListener('click',nextStep)}function check(){const answer=input.value.trim().toLowerCase(),correct=w.word.toLowerCase(),ok=answer===correct;scheduleByQuiz(w,ok);document.getElementById('checkBtn').disabled=true;input.disabled=true;showResult(ok);saveState(state)}document.getElementById('checkBtn').addEventListener('click',check);input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!document.getElementById('checkBtn').disabled)check()})}
function renderSummary(){const s=ensureTodaySession();finalizeSessionIfNeeded();setTitle('今日完成',true);setNav('');const total=s.activeIds.length,acc=(s.stats.correct+s.stats.wrong)?Math.round(s.stats.correct/(s.stats.correct+s.stats.wrong)*100):0,wrongList=s.wrongIds.map(id=>state.words[id]);document.getElementById('view').innerHTML=`<div class="card hero" style="text-align:center"><div class="small">今天任務完成，今天的字都練熟了</div><div class="section">${total} / ${total}</div><div class="meaning">作答正確率 ${acc}%</div></div><div class="grid"><div class="metric"><div class="ml">綠燈</div><div class="mv">${s.stats.green}</div></div><div class="metric"><div class="ml">黃燈</div><div class="mv">${s.stats.yellow}</div></div><div class="metric"><div class="ml">紅燈</div><div class="mv">${s.stats.red}</div></div><div class="metric"><div class="ml">答對次數</div><div class="mv">${s.stats.correct}</div></div></div><div class="card"><div class="section">今天錯過的單字</div>${wrongList.length?wrongList.map(w=>`<div class="kv"><span>${w.word}</span><span class="muted">${w.meaning}</span></div>`).join(''):'<div class="muted">今天沒有錯字</div>'}</div><div class="stack"><button class="btn primary" id="backHomeBtn" type="button">回首頁</button></div>`;document.getElementById('backHomeBtn').addEventListener('click',()=>go('home'))}
function renderWordDetail(){const w=state.words[state.selectedWordId];if(!w){go('list');return}const exampleEn=getExampleEn(w),exampleZh=getExampleZh(w);setTitle('單字詳情',true);setNav('');document.getElementById('view').innerHTML=`<div class="card"><div class="word">${w.word}</div><div class="phon">${w.phonetic}</div><div class="meta"><span class="badge">${w.pos}</span><span class="badge">${w.topic}</span><span class="badge">L${w.level}</span></div><div class="meaning">${w.meaning}</div><div class="stack" style="margin-top:12px"><button class="btn secondary" id="speakBtn" type="button">🔊 聽發音</button></div><div class="section" style="font-size:18px;margin-top:16px">英文例句</div><div class="exen">${exampleEn}</div><div class="section" style="font-size:18px;margin-top:16px">中文例句</div><div class="exzh">${exampleZh}</div><div class="section" style="font-size:18px;margin-top:16px">熟練度</div><div class="kv"><span>目前燈號</span><span class="dot ${masteryColor(w.mastery)}"></span></div><div class="kv"><span>已學過</span><span>${w.seen?'是':'否'}</span></div><div class="kv"><span>答錯次數</span><span>${w.wrongCount||0}</span></div><div class="stack" style="margin-top:16px"><button class="btn primary" id="backListBtn" type="button">回單字庫</button></div></div>`;document.getElementById('speakBtn').addEventListener('click',()=>speakWord(w.word));document.getElementById('backListBtn').addEventListener('click',()=>go('list'))}
function renderList(){setTitle('單字庫',false);setNav('list');const all=getStudyWords(),topics=['all',...new Set(all.map(w=>w.topic))],topicFilter=state.filters.topic||'all',levelFilter=state.filters.level||'all';const filtered=all.filter(w=>topicFilter==='all'||w.topic===topicFilter).filter(w=>levelFilter==='all'||String(w.level)===levelFilter).sort((a,b)=>a.word.localeCompare(b.word));const topicOptions=topics.map(t=>`<option value="${t}" ${t===topicFilter?'selected':''}>${t==='all'?'全部主題':t}</option>`).join('');const levelOptions=['all','1','2','3'].map(l=>`<option value="${l}" ${l===levelFilter?'selected':''}>${l==='all'?'全部等級':'Level '+l}</option>`).join('');const rows=filtered.map(w=>`<div class="row word-row" data-id="${w.id}" role="button"><span class="dot ${masteryColor(w.mastery)}"></span><div><div class="wsmall">${w.word}</div><div class="muted">${w.pos} ｜ ${w.meaning}</div></div><button class="ghost speak-only" data-speak="${w.word}" type="button">🔊</button></div>`).join('');document.getElementById('view').innerHTML=`<div class="card notice"><div class="small">字庫已獨立成 words_library.js，之後你只要抽換那個檔案就能換整套單字。</div></div><div class="filter"><select id="topicFilter" class="select">${topicOptions}</select><select id="levelFilter" class="select">${levelOptions}</select></div><div class="card"><div class="small">共 ${filtered.length} 個正式單字</div>${rows}</div>`;document.getElementById('topicFilter').addEventListener('change',e=>{state.filters.topic=e.target.value;saveState(state);renderList()});document.getElementById('levelFilter').addEventListener('change',e=>{state.filters.level=e.target.value;saveState(state);renderList()});document.querySelectorAll('.word-row').forEach(el=>el.addEventListener('click',()=>openWordDetail(Number(el.dataset.id))));document.querySelectorAll('.speak-only').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();speakWord(btn.dataset.speak)}))}
function renderStats(){setTitle('學習統計',false);setNav('stats');const all=getStudyWords(),learned=all.filter(w=>w.seen).length,dueToday=all.filter(w=>w.nextReview&&w.nextReview<=todayStr()).length,historyRows=(state.history||[]).slice(0,7).map(h=>`<div class="kv"><span>${h.date}</span><span class="muted">${h.correct}/${h.total}</span></div>`).join('');document.getElementById('view').innerHTML=`<div class="grid"><div class="metric"><div class="ml">已學過</div><div class="mv">${learned}</div></div><div class="metric"><div class="ml">今日到期複習</div><div class="mv">${dueToday}</div></div><div class="metric"><div class="ml">最近完成</div><div class="mv">${(state.history||[]).length}</div></div><div class="metric"><div class="ml">正式字庫</div><div class="mv">${all.length}</div></div></div><div class="card"><div class="section">最近學習紀錄</div>${historyRows||'<div class="muted">還沒有完成的紀錄</div>'}</div>`}
function renderSettings(){setTitle('設定',false);setNav('settings');const settings=readSettings(),cloudReady=(settings.apiBaseUrl||'').trim()?'已設定':'未設定',syncCode=getOrCreateSyncCode();document.getElementById('view').innerHTML=`<div class="card"><div class="section">版本資訊</div><div class="kv"><span>版次</span><span>v7.4</span></div><div class="kv"><span>正式字庫</span><span>${getStudyWords().length}</span></div><div class="kv"><span>同步代碼</span><span class="mono">${syncCode}</span></div><div class="kv"><span>雲端 API</span><span>${cloudReady}</span></div><div class="kv"><span>最後雲端讀取</span><span class="muted">${state.sync&&state.sync.lastCloudLoad?state.sync.lastCloudLoad.slice(0,19).replace('T',' '):'尚未'}</span></div><div class="kv"><span>最後雲端保存</span><span class="muted">${state.sync&&state.sync.lastCloudSave?state.sync.lastCloudSave.slice(0,19).replace('T',' '):'尚未'}</span></div></div><div class="card"><div class="section">雲端同步設定</div><div class="muted">換手機時，用同一個 Worker API 與同步代碼即可載回進度。</div><input id="apiInput" class="input" placeholder="貼上 Worker API 網址" value="${settings.apiBaseUrl||''}"><input id="syncCodeInput" class="input mono" placeholder="輸入或貼上同步代碼" value="${syncCode}"><div class="stack"><button class="btn primary" id="saveApiBtn" type="button">保存同步設定</button><button class="btn secondary" id="syncNowBtn" type="button">立刻同步到雲端</button><button class="btn secondary" id="loadCloudBtn" type="button">從雲端載入進度</button><button class="btn light" id="copyCodeBtn" type="button">複製同步代碼</button></div></div>`;document.getElementById('saveApiBtn').addEventListener('click',()=>{const api=document.getElementById('apiInput').value.trim(),code=document.getElementById('syncCodeInput').value.trim();if(!code){alert('請先輸入同步代碼');return}const s=readSettings();s.apiBaseUrl=api;s.syncCode=code;writeSettings(s);alert('同步設定已保存');render()});document.getElementById('syncNowBtn').addEventListener('click',async()=>{const code=document.getElementById('syncCodeInput').value.trim();if(!setSyncCode(code)){alert('請先輸入同步代碼');return}const ok=await saveCloudState(state);if(ok){state.sync=state.sync||{};state.sync.lastCloudSave=new Date().toISOString();saveLocalState(state);alert('已同步到雲端');render()}else{alert('同步失敗，請確認 Worker 網址是否正確')}});document.getElementById('loadCloudBtn').addEventListener('click',async()=>{const code=document.getElementById('syncCodeInput').value.trim();if(!setSyncCode(code)){alert('請先輸入同步代碼');return}const cloud=await loadCloudStateIfPossible();if(cloud){state=cloud;saveLocalState(state);alert('已從雲端載入進度');render()}else{alert('讀取失敗，請確認 Worker 網址、同步代碼或雲端資料')}});document.getElementById('copyCodeBtn').addEventListener('click',async()=>{const code=document.getElementById('syncCodeInput').value.trim();try{await navigator.clipboard.writeText(code);alert('同步代碼已複製')}catch{alert('複製失敗，請手動複製')}})}
function render(){const route=state.currentRoute||'home';if(route==='home')return renderHome();if(route==='study')return renderStudy();if(route==='quiz')return renderQuiz();if(route==='summary')return renderSummary();if(route==='list')return renderList();if(route==='stats')return renderStats();if(route==='settings')return renderSettings();if(route==='word')return renderWordDetail();renderHome()}
window.speakWord=speakWord;
let state=loadLocalState();
(async()=>{const cloud=await loadCloudStateIfPossible();if(cloud){state=cloud;saveLocalState(state)}ensureTodaySession();finalizeSessionIfNeeded();render()})();
